[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "SpaGNNs"
authors = [{name = "ChangXu", email = "changxu@nus.edu.sg"}]
dynamic = ["version", "description"]
